security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_INVITADO, ROLE_GESTORSTOCK]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home_page
            logout:
                path: app_logout
                target: app_login
            login_throttling:
                max_attempts: 3
                interval: '1 minutes'

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/home/page, roles: [ROLE_USER, ROLE_ADMIN, ROLE_GESTORSTOCK] }
        - { path: ^/product, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/add-used-machinery, roles: [ROLE_ADMIN, ROLE_GESTORSTOCK ] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
